[package]
name = "sesh"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive", "env"] }
ctrlc = "3.4.6"
hostname = "0.4.1"
users = "0.11.0"

[build-dependencies]
roff = "0.2.2"
